blueprint:
  name: Hue Tap Gen 1 (Direct MQTT Topic)
  description: "Bypasses device entities to avoid UI errors."
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: "Copy from your Z2M screenshot: zigbee2mqtt/Hue Tap switch/action"
      default: "zigbee2mqtt/Hue Tap switch/action"
    button_1:
      name: "Button 1 (·)"
      default: []
      selector:
        action: {}
    button_2:
      name: "Button 2 (··)"
      default: []
      selector:
        action: {}
    button_3:
      name: "Button 3 (···)"
      default: []
      selector:
        action: {}
    button_4:
      name: "Button 4 (····)"
      default: []
      selector:
        action: {}

mode: restart

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

action:
  - choose:
      - conditions: '{{ trigger.payload == "press_1" }}'
        sequence: !input button_1
      - conditions: '{{ trigger.payload == "press_2" }}'
        sequence: !input button_2
      - conditions: '{{ trigger.payload == "press_3" }}'
        sequence: !input button_3
      - conditions: '{{ trigger.payload == "press_4" }}'
        sequence: !input button_4
