blueprint:
  name: Hue-Style Motion Lighting (generic v1.1)
  description: >
    “Philips-Hue-like” motion lighting for any mix of binary_sensor and light
    entities.  • Multiple sensors and lights • Day / night brightness split
    • Fade-in / fade-out • Optional lux, manual disable, or media-player block.

  domain: automation

  input:
    occupancy_sensors:
      name: Occupancy / Motion sensors
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
          multiple: true

    light_targets:
      name: Lights to control
      selector:
        entity:
          domain: light
          multiple: true

    off_delay:
      name: Off-delay (seconds)
      default: 180
      selector:
        number:
          min: 0
          max: 1800
          unit_of_measurement: s
          mode: box

    illuminance_entity:
      name: (Optional) Illuminance sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance
      default: ""

    illuminance_max:
      name: Lux threshold
      default: 6
      selector:
        number:
          min: 1
          max: 3000
          unit_of_measurement: lx
          mode: box

    day_brightness:
      name: Day brightness (%)
      default: 75
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    night_brightness:
      name: Night brightness (%)
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    day_kelvin:
      name: Day colour temp (K)
      default: 4500
      selector:
        number:
          min: 1500
          max: 6500
          step: 100
          unit_of_measurement: K

    night_kelvin:
      name: Night colour temp (K)
      default: 3000
      selector:
        number:
          min: 1500
          max: 6500
          step: 100
          unit_of_measurement: K

    night_start:
      name: Night-mode starts
      default: "22:00:00"
      selector:
        time:

    night_end:
      name: Night-mode ends
      default: "07:00:00"
      selector:
        time:

    fade_in_time:
      name: Fade-in (s)
      default: 1.5
      selector:
        number:
          min: 0
          max: 15
          step: 0.5
          unit_of_measurement: s

    fade_out_time:
      name: Fade-out (s)
      default: 3
      selector:
        number:
          min: 0
          max: 15
          step: 0.5
          unit_of_measurement: s

    disable_switch:
      name: (Optional) Manual disable switch
      selector:
        entity:
          domain: input_boolean
      default: ""

    media_player_block:
      name: (Optional) Disable when media-player is playing
      selector:
        entity:
          domain: media_player
      default: ""

# ─────────── INTERNAL VARIABLES ───────────
variables:
  sensors: !input occupancy_sensors
  lights:  !input light_targets
  disable_sw: !input disable_switch
  media_ent:  !input media_player_block
  lux_ent: !input illuminance_entity
  lux_max: !input illuminance_max
  off_delay: !input off_delay
  night_start: !input night_start
  night_end:   !input night_end
  night_brightness: !input night_brightness
  day_brightness:   !input day_brightness
  night_kelvin:     !input night_kelvin
  day_kelvin:       !input day_kelvin
  fade_in:  !input fade_in_time
  fade_out: !input fade_out_time

mode: restart
max_exceeded: silent

# ─────────── TRIGGER ───────────
trigger:
  - platform: state
    entity_id: !input occupancy_sensors

# ─────────── GLOBAL CONDITIONS ───────────
condition:
  - condition: template          # manual disable
    value_template: >
      {{ disable_sw == '' or is_state(disable_sw, 'off') }}
  - condition: template          # media-player override
    value_template: >
      {{ media_ent == '' or states(media_ent) in ['off','idle','standby'] }}

# ─────────── ACTIONS ───────────
action:
  - choose:
      # ── TURN-ON branch ──────────────────────────────
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          # optional lux gate
          - condition: template
            value_template: >
              {{ lux_ent == '' or (states(lux_ent) | float(9999)) < lux_max }}

          # night-mode?
          - variables:
              night_mode: >
                {% set now_t = now().time() %}
                {% set start = strptime(night_start, '%H:%M:%S').time() %}
                {% set end   = strptime(night_end,   '%H:%M:%S').time() %}
                {% if start < end %}
                  {{ start <= now_t < end }}
                {% else %}
                  {{ now_t >= start or now_t < end }}
                {% endif %}

          - service: light.turn_on
            target:
              entity_id: !input light_targets
            data:
              transition: "{{ fade_in | float }}"
              brightness_pct: "{{ night_brightness if night_mode else day_brightness }}"
              kelvin: "{{ night_kelvin if night_mode else day_kelvin }}"

      # ── TURN-OFF branch ─────────────────────────────
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - wait_template: >
              {{ expand(sensors)
                 | selectattr('state','eq','on')
                 | list
                 | length == 0 }}
            timeout: "{{ off_delay | int }}"
            continue_on_timeout: false

          - service: light.turn_off
            target:
              entity_id: !input light_targets
            data:
              transition: "{{ fade_out | float }}"
